### ISSUE TITLE
下载依赖，调用成功，截完图，点击ok和cancel失败，鼠标消失，在运行时控制台报错：

### ISSUE THREAD

**Issue by CoderLzz** [youngerheart/electron-vue-screen-capture#1]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders     
> <!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=./favicon.ico><link href=./public/css/screenCapture.23bca4c6.css rel=preload as=style><link href=./public/js/chunk-vendors.d1dc4f70.js rel=modulepreload as=script><link href=./public/js/screenCapture.b573eab9.js rel=modulepreload as=script><link href=./public/css/screenCapture.23bca4c6.css rel=stylesheet></head><body draggable=false><noscript><strong>We're sorry but project doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script type=module src=./public/js/chunk-vendors.d1dc4f70.js></script><script type=module src=./public/js/screenCapture.b573eab9.js></script><script>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script></body></html>

**Comment by youngerheart** [comment]
你这边的electron版本是多少？当时我只试了8.x ~ 9.X，晚些我试试新版本的情况。

**Comment by CoderLzz** [comment]
9.0

**Comment by CoderLzz** [comment]
electron版本9.3.1，就时截完图之后，点击ok和cancel按钮没有任何反应，没有调用对应的方法，我是使用Vue CLI Plugin Electron Builder搭建的项目中使用该插件

**Comment by youngerheart** [comment]
hi，这边做了一轮修复并更新了文档。在截图完成/取消后考虑到对图像的自定义处理，将关闭截图窗口逻辑设置为了手动，具体如下：
```js
// 监听截图完成/取消事件
ipcMain.on('getCaptureData', (e, data) => {
  // data为图像的base64。在取消截图时返回false.
  if (typeof data === 'string') targetWin.send('getCaptureData', data);
  // 对图像数据操作完成后，手动关闭截图窗口
  close();
});
```
在0.0.10版本试试吧~
